plugins {
    id 'java-library'
}

dependencies {
    api project(':erp-domain')
    api project(':erp-common')

    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.springframework.boot:spring-boot-starter-data-mongodb'
    api 'org.springframework.boot:spring-boot-starter-data-redis'
    api 'org.springframework.boot:spring-boot-starter-cache'
    runtimeOnly 'org.postgresql:postgresql'

    // AWS SDK v2 — S3
    implementation 'software.amazon.awssdk:s3:2.25.6'

    // REST Web Client
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Mail HTML
    api 'org.springframework.boot:spring-boot-starter-mail'
    api 'org.springframework.boot:spring-boot-starter-thymeleaf'
}
